### ISSUE TITLE
getTempusIntegratorStatus build error

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#239] opened 2018-01-03 15:31 UTC
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=64961

**Comment by ikalash** [comment] 2018-01-03 19:58
I am guessing the LCM builds on @lxmota build against master Trilinos instead of develop.  Can someone please confirm?  I think the issue is I made changes to Trilinos (develop branch) that go hand-in-hand with Albany, so Albany will not build against master Trilinos until the changes in develop get pushed to master.

**Comment by ibaned** [comment] 2018-01-03 20:26
@lxmota, we need to do all our builds against Trilinos develop, and probably teach LCM users to do the same. Its become apparent that Trilinos master is not useful to anyone we know.

**Comment by bgranzow** [comment] 2018-01-03 21:08
For what it's worth, I just tried to compile Albany + Trilinos (develop branch) at the SHAs
https://github.com/trilinos/Trilinos/commit/39cd06d8671729488b1ab78931ba6b49a7352eee
Albany: https://github.com/gahansen/Albany/commit/3785a5a0173c64460b692481707e6d0d2ad7f361
and got the compilation error:
```
/lore/granzb/albany/src/LCM/solvers/Schwarz_Alternating.cpp: In member function 'void LCM::SchwarzAlternating::SchwarzLoopDynamics() const':
/lore/granzb/albany/src/LCM/solvers/Schwarz_Alternating.cpp:808:37: error: 'class Piro::TempusSolver<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >' has no member named 'getTempusIntegratorStatus'
         status = piro_tempus_solver.getTempusIntegratorStatus();
```
which is presumably the same error that this issue refers to (I can't see the internal Sandia dashboard)

**Comment by bgranzow** [comment] 2018-01-03 21:17
Whoops, I pointed Albany to an incorrect (older) Trilinos build. My previous comment is likely irrelevant. Sorry about that.

**Comment by ikalash** [comment] 2018-01-03 21:57
No worries @bgranzow .  I just double checked and this should not be a problem when building against develop Trilinos.

**Comment by lxmota** [comment] 2018-01-09 19:23
Sorry for the silence. I just came back from travel.

We need to discuss this at the next Albany meeting. On purpose I avoided using Trilinos develop for our users because quite frequently it is broken.

So when changes in Trililinos were introduced that required changes in Albany, I held off the changes in Albany until I saw them propagated to Trilinos master.

This of course introduced frustrating delay.

On the other hand, I hesitate to push Trilinos develop as the default for our users due to its instability. Maybe today the situation of better?

**Comment by ibaned** [comment] 2018-01-09 22:35
If the choice is between Trilinos develop and master, develop is the one that is better for us because they are both unstable for Albany and develop gets new features and bug fixes first. We can try to set up our own "Albany Trilinos master" which is stable via our own testing, other Sandia applications have done this. Until then though, develop is the next best choice.

**Comment by gahansen** [comment] 2018-01-09 23:30
I'd propose that we move to an automatic version of Alejandro's "last-known-commits-that-work" idea. I think I could save-off the Trilinos develop HEAD sha and the current Albany HEAD sha as part of the nightly test run, of say the Albany64BitClang test. If that nightly completes without error (the tests are 100% green), we could post those sha's to a wiki page perhaps and direct the users to that information (hopefully internal to the test script).  I'll add some scripting to the tests to attempt this if folks think it is worthwhile to try this idea out.

**Comment by lxmota** [comment] 2018-01-09 23:36
That wiki page with the good commits is supposed to be updated automatically. I need to find out why it stopped working.

Yes, I think having an automated page like that would be very useful for users.

**Comment by gahansen** [comment] 2018-01-09 23:40
I wonder where the best place to post the info might be? Perhaps add to Alejandro's current automated process - or should we send it out via an email to the Albany mailing list? Perhaps we should make a separate mailing list just for these messages?

**Comment by lxmota** [comment] 2018-01-09 23:48
Personally I prefer the wiki page approach. I'm open to re-purpose the one I created for this.

My "good commit" test was looser in the sense that the pass condition was that the code compiled. I did it that way because sometimes there would be one or two failing tests that weren't fixed quickly, while relevant fixes or features were pushed to the code that needed to be used right away.

**Comment by gahansen** [comment] 2018-01-10 16:13
How about we allow for an arbitrary number of test failures - say 10 - and still call the commits "good," instead of the 100% green criteria I mentioned above? That would allow for a small number of tests to fail. If we have more than 10 fail, something is likely askew.

**Comment by ibaned** [comment] 2018-01-10 16:15
I don't know, I thought we just conducted a campaign to get all-green tests so we could use that to our advantage. We've had Trilinos cause problems for us that were only detected by one or two tests.

**Comment by gahansen** [comment] 2018-01-10 16:30
Yea - I'm with Dan. If a single test fails someone needs to take a look and fix it before the next nightly. If we are a day or two behind on the "good commits" so be it - this will err towards robust "good commits" for our users which they will likely appreciate.

**Comment by mperego** [comment] 2018-01-10 16:42
@ibaned @gahansen agreed.

**Comment by lxmota** [comment] 2018-01-10 17:17
Fair enough. Let’s make the good commits depend on an all-green dashboard.

**Comment by gahansen** [comment] 2018-01-12 16:26
I was able to rig up an update mechanism to manage the wiki page at:

https://github.com/gahansen/Albany/wiki/Current-Working-Sha

based on the results of the nightly Albany64BitClang. The code starts at line 778 of:

https://github.com/gahansen/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/ctest_nightly.cmake

However, I am going to move this to run on the Jenga test machine at RPI so these commits reflect the results shown on the dashboard at:

https://my.cdash.org/index.php?project=Albany

which will add value for our non-Sandia users also.

I am going to close this issue as it has drifted from the original topic - we can reopen a new one if we need to modify / extend the "Good Commits" feature.

**Closed by gahansen** 2018-01-12 16:26 UTC

**Comment by ibaned** [comment] 2018-01-12 16:39
@gahansen note that we have no ETA on when Jenga will be usable for nightly jobs again.
