### ISSUE TITLE
failing "Use Serial Mesh" tests in nightly test harness

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#102] opened 2017-03-31 17:48 UTC
This is a machine-specific issue, not a bug, but I am having a hard time figuring it out, so I am posting an issue in an attempt to get some help.

I recently upgraded the OS on my testing workstation camobap from Fedora 21 to Fedora 25.  With the upgrade, it seems all the tests that have "Use Serial Mesh = true" fail, with an error like this: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=2735890&build=50687 .  I know that this can happen when one does not set 

-D TPL_Netcdf_PARALLEL:BOOL=ON \

or when the netcdf the build points to is not parallel.  However, I have the flag in my Trilinos and my netcdf _is_ parallel.  My netcdf headers/libs are actually copied from another machine with the same OS (@lxmota's algol machine) where this issue does not occur.  Does anyone have any suggestions for how to diagnose / resolve this issue, so we have a cleaner CDash?

**Comment by bartgol** [comment] 2017-03-31 19:25
@ikalash I don't have access to that link, so I am not sure if it's the same problem I have (had). When trying to load a serial mesh and partition it on the fly, I sometimes got an error form stk saying that the database mesh.exo could  not be read. Is this what you are experiencing?

I tried to look into that but could not fix it. Eventually I ended up decomposing the mesh by hand before each execution, so that I didn't need Use Serial Mesh anymore.

I am not sure if this is a bug, it may just have to do with some configuration of netcdf and/or trilinos. Any thought/experience on this to be shared would be really appreciated though.

**Comment by ibaned** [comment] 2017-03-31 19:30
@bartgol that is indeed the issue in the link. I was convinced that `TPL_Netcdf_PARALLEL` was the key to resolving that, but I guess not.

**Comment by ibaned** [comment] 2017-03-31 19:53
@ikalash can you share the output of this ?
```bash
ls $ALBANY_BUILD_DIR/tests/small/Ioss2D
```

**Comment by ikalash** [comment] 2017-03-31 20:11
@ibaned .  Sure, here it is: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=2736310&build=50703 .  That test runs fine.  @mperego and I encountered this issue on Hopper awhile ago and were never able to resolve it; so we just did @bartgol 's fix.  But that does not work if the issue shows up on a machine where testing is done -- all the tests that use the "Use Serial Mesh" option will fail.  @lxmota said he saw the issue when netcdf was not build with parallel-netcdf; but that fix does not work on my machine for some reason, even though I am using exactly the same netcdf/parallel-netcdf at @lxmota's machines, with the same OS.

**Comment by ikalash** [comment] 2017-03-31 20:14
@ibaned , I can give you an account on my machine, if you'd like, so you can try to reproduce the error there; I will not have access to the machine 4/3-4/11, as I will be out of the country.

**Comment by ibaned** [comment] 2017-03-31 20:15
> I can give you an account on my machine

Thanks, I think thats a good idea.

**Comment by ikalash** [comment] 2017-03-31 20:23
@ibaned , will do.  I'll follow up offline.

**Comment by ikalash** [comment] 2017-05-08 17:50
Your recent commit seems to have fixed the problem, @ibaned - thanks!  A follow up question that has come up before at the Albany meetings is whether logic should be added to detect if the user has the right version of netcdf (one that is parallel) and to only run the "Use Serial Mesh" tests if a parallel netcdf exists.  What do people think about this?

**Comment by ibaned** [comment] 2017-05-08 17:51
I forgot this was already a GitHub issue, here is the solution from an email I sent earlier:
Here are the details on the Serial Mesh issue, which I just got fixed right before the call:
 
The mpiexec in question is this one:

```
/usr/lib64/openmpi/bin/mpiexec
```
 
If you run that command, it will put `/usr/lib64/openmpi/lib` in LD_LIBRARY_PATH right before running the program, and the problem is that
 
```
/usr/lib64/openmpi/lib/libnetcdf.so.11.0.4
```
 
Is a non-parallel version of netcdf, probably installed by the Fedora package manager, so that would get linked to Albany instead of the one the user built by hand.
The way to disable this behavior of `mpiexec` is to pass the `--noprefix` flag:
 
```
/usr/lib64/openmpi/bin/mpiexec --noprefix
```
 
I just pushed Albany commit e7e24a7, after that commit you can add this to your CMake configuration:
 
```
-DALBANY_MPI_EXEC_LEADING_OPTIONS:STRING="--noprefix" \
```

**Comment by ibaned** [comment] 2017-05-08 17:52
As for detection, I'll have to look into it to see if there is a way we can detect this support in NetCDF at compile or configure time.

**Comment by ikalash** [comment] 2017-05-08 17:54
Thanks, @ibaned.  I guess I can close this issue and we can open a new one having to do with the detection.  Let me know if you disagree.

**Comment by ibaned** [comment] 2017-05-08 17:54
works for me.

**Closed** 2017-05-08 17:55 UTC
Labels: question
