### ISSUE TITLE
minitensor related compilation error

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#109] opened 2017-04-13 21:50 UTC
Is anyone else getting the following minitensor-related compilation error in Albany?

/home/ikalash/Albany/src/LCM/evaluators/BifurcationCheck_Def.hpp: In member function ‘minitensor::Vector<typename Sacado::mpl::apply<Sacado::Fad::DFad<double>, typename Sacado::mpl::apply<Sacado::Fad::DFad<double>, typename EvalT::ScalarT>::type>::type, 3u> LCM::BifurcationCheck<EvalT, Traits>::tangent_get_normal(minitensor::Vector<typename Sacado::mpl::apply<Sacado::Fad::DFad<double>, typename Sacado::mpl::apply<Sacado::Fad::DFad<double>, typename EvalT::ScalarT>::type>::type, 2u>&)’:
/home/ikalash/Albany/src/LCM/evaluators/BifurcationCheck_Def.hpp:1480:15: error: ‘ZEROS’ is not a member of ‘minitensor’
     normal(3, minitensor::ZEROS);

I saw there was a related checkin to Trilinos by @lxmota , so I have pulled / rebuilt Trilinos, but am still getting the error.

**Comment by lxmota** [comment] 2017-04-14 00:05
Sorry about this. There have been some significant changes to MiniTensor and the corresponding Albany code because of requests from the production code.

The problem is that our users use the Trilinos master branch, and so I haven't pushed the corresponding Albany changes.

Not sure what we can do to prevent this situation from happening in the future, where different users use the Trilinos master branch and others the Trilinos develop branch.

That is why I think there should also be two branches for Albany.

But that does not solve your problem. I could suggest to reset your Trilinos branch to the commit just prior to my MiniTensor changes:

https://github.com/trilinos/Trilinos/commit/4f0a31ac5f9e5d41425cb980d57f92ffc02f50ed

If this is not acceptable, let's discuss to try to find a better solution.

**Comment by ikalash** [comment] 2017-04-14 00:08
No problem.  My workaround was to switch to master for now, which should be OK for the time being.  I'll switch my nightlies to master too so that they do not famil.

**Comment by lxmota** [comment] 2017-04-18 21:42
Fixed by https://github.com/gahansen/Albany/commit/e6f5c3ee4294ebbeee7d5c7cd2c4907bb6791130 and https://github.com/gahansen/Albany/commit/a6c2d31a7ebb965873cd7f26b8d78cd77b4c73c3.

**Closed by lxmota** 2017-04-18 21:42 UTC
Labels: LCM
