### ISSUE TITLE
"Test Values" for regression results ignored?

### ISSUE THREAD

**Issue by bgranzow** [gahansen/Albany#31] opened 2017-01-24 15:31 UTC
Using the Elasticity2DTriangles inputT.xml input file as an example:

https://github.com/gahansen/Albany/blob/master/examples/LCM/Elasticity2DTriangles/inputT.xml

It appears that the regression comparison for the "Solution Average" response function is not actually compared against when running the problem. i.e. I can change the Test Value on this line:

https://github.com/gahansen/Albany/blob/master/examples/LCM/Elasticity2DTriangles/inputT.xml#L109

and the number of failed comparisons at the end of the Albany run will still be 0.
Is this expected behavior? I think I recall this behaved differently a few years ago.

Cheers,
Brian

**Comment by ibaned** [comment] 2017-03-10 21:43
Well, it turns out this was serious issue, and it is now fixed. Commit b3f6770 caused the `AlbanyT` executable to stop doing Response Tests for regression, if the input contained physical parameters and the sensitivities of responses with respect to those parameters was not computed. The main fix for this which I just pushed is 1a15fe1. Furthermore, in f659097, I added tests with CMake's `WILL_FAIL` property to ensure that `AlbanyT` does fail with a non-zero error code if the Response Tests fail. This should help protect against such an important system being disabled again. Luckily, the results of most tests on my machine seem unaffected, meaning that they didn't regress while the regression testing system was broken... we'll see what the dashboards say.

**Closed by ibaned** 2017-03-10 21:43 UTC
Labels: bug
