### ISSUE TITLE
Broken Schwarz tests due to YAML

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#186] opened 2017-10-02 15:08 UTC
This may be related to (or the same as) issue #185.  It looks like over the weekend the following Schwarz tests failed 

Parallel_Dynamic_Cubes_NewmarkExplicitAForm_LumpedMass_Tempus  
SchwarzBarCPMatrixFree_np1  
SchwarzBarCPModified_np1  

due to a Yaml parser error

p=5: *** Caught standard std::exception of type 'Teuchos::ParserFail' :

 error: Parser failure at line 40 column 1 of parseYamlText
 ]
 Expected one of {',', ]}
 Got: NEWLINE
 Parser was in state 115
 

p=7: *** Caught standard std::exception of type 'Teuchos::ParserFail' :

 error: Parser failure at line 40 column 1 of parseYamlText
 ]
 Expected one of {',', ]}
 Got: NEWLINE
 Parser was in state 115

I saw a lot of activity over the weekend having to do with Yaml by @ibaned .  Dan, is this related to the changes you were making over the weekend?

**Comment by ikalash** [comment] 2017-10-02 15:56
Here is a link to the CDash which shows the error: 

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=60347

**Comment by ikalash** [comment] 2017-10-02 16:32
I have resolved this issue.  Need to use quotes now in yaml files if giving relative paths, e.g., ../input.yaml should be '../input.yaml'.

**Comment by ibaned** [comment] 2017-10-02 18:11
Yes its the same issue and for now that workaround is necessary, until the fix trilinos/Trilinos#1799 is merged.

**Comment by lxmota** [comment] 2017-10-03 19:48
@ibaned  I'll ask this here, not sure if there is a more appropriate thread. Thanks for fixing gahansen/Albany#186, it works now, except for the following:

If there are empty lines at the end of a YAML input file, I get the following error:

```
Initializing material database from materials_01.yaml

p=0: *** Caught standard std::exception of type 'Teuchos::ParserFail' :

 error: Parser failure at line 18 column 1 of materials_01.yaml
 Expected one of {", #, ', -, ., DEDENT, OTHERCHAR}
 Got: NEWLINE
 Parser was in state 160
```

The error goes away by removing the empty lines at the end of the file.

I'm sure that users will have input files with empty lines at the end, so it seems to me that it would be prudent to handle this case by just ignoring them.

**Comment by ibaned** [comment] 2017-10-03 21:52
@lxmota part of the problem is that this line is not empty, in fact it contains leading indentation (same number of tabs as line above). If I remove those tabs and keep just the newline, the parser accepts it. I may still try to extend the grammar to resist this, but note that its those tabs that actually cause the problem, the code should handle truly empty lines ok.

**Comment by lxmota** [comment] 2017-10-03 21:55
@ibaned Ah ok. I think extra tabs in the file are bad. Let's leave the behavior as it is then. Perhaps a hint in the error message that that could be the problem would be helpful.

**Closed** 2017-10-04 21:15 UTC
Labels: bug, LCM
