### ISSUE TITLE
Failing tests in nightly CDash 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#97] opened 2017-03-27 14:18 UTC
Most of the tests in my Albany nightly CDash failed yesterday, it looks like due to failed comparisons:

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=50475

It seems some of the transient problems are blowing up.

**Comment by ibaned** [comment] 2017-03-27 14:23
Not just transient: you know something is wrong when SteadyHeat1D fails:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=2727709&build=50475

The non-linear solver is diverging...

**Comment by ibaned** [comment] 2017-03-27 17:47
I confirm that trilinos/Trilinos@736f3cf and Albany at d730ced don't have these symptoms, so something in Trilinos broke this. Will look for what it is...

**Comment by ibaned** [comment] 2017-03-27 17:49
I guess I should also mention I confirm the failures with trilinos/Trilinos@a06d907

**Comment by etphipp** [comment] 2017-03-27 17:57
It might be this for Tpetra-based tests:

https://github.com/trilinos/Trilinos/issues/1187

There was a serious (but simple) bug introduced in Tpetra CrsMatrix import/export.

**Comment by ibaned** [comment] 2017-03-27 17:59
@etphipp has a fix been pushed to Trilinos develop ?

**Comment by etphipp** [comment] 2017-03-27 18:07
Not yet.  I believe Mark is trying to add a test to reproduce the error I was seeing in Stokhos.  Here is a patch if you want to see if it fixes the Albany tests:

diff --git a/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp b/packages/tpetra
index 30eba0f..7e8d4b7 100644
--- a/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
+++ b/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
@@ -5924,8 +5924,8 @@ namespace Tpetra {
     // Since the matrix is locally indexed on the calling process, we
     // have to use its column Map (which it _must_ have in this case)
     // to convert to global indices.
-    const offset_type rowBeg = this->lclMatrix_.graph.row_map[numEnt];
-    const offset_type rowEnd = this->lclMatrix_.graph.row_map[numEnt + 1];
+    const offset_type rowBeg = this->lclMatrix_.graph.row_map[lclRow];
+    const offset_type rowEnd = this->lclMatrix_.graph.row_map[lclRow + 1];
 
     auto indIn = Kokkos::subview (this->lclMatrix_.graph.entries,
                                   pair_type (rowBeg, rowEnd));

**Comment by etphipp** [comment] 2017-03-27 18:08
Githup messed that all up.  The patched is attached
[here](https://github.com/gahansen/Albany/files/873357/tpetra_patch.txt)

**Comment by ibaned** [comment] 2017-03-27 18:12
@etphipp Thanks, I'll give it a shot (just from what I know about row maps, it seems like its definitely needed).

PS - in the future, just put triple backticks before and after anything you want kept verbatim.

**Comment by ibaned** [comment] 2017-03-27 18:53
@etphipp Confirmed your patch fixes the fundamental tests ! Lets pursue this in trilinos/Trilinos#1187

**Comment by etphipp** [comment] 2017-03-27 19:05
I believe Mark just pushed this change.

**Comment by ibaned** [comment] 2017-03-27 19:07
Yep, building and testing with Trilinos develop now

**Comment by ibaned** [comment] 2017-03-27 19:48
Confirmed this is fixed in Trilinos develop. I'm going to close this issue on that assumption, please reopen if tomorrow's CDash shows differently.

**Closed by ibaned** 2017-03-27 19:48 UTC
Labels: bug
